# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: UTBadgeChain
email: maxwell.lincoln@austin.utexas.edu
description: > # this means to ignore newlines until "baseurl:"
  The efforts of the University of Texas at Austin to implement a blockchain based badging system.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://utbadgechain.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
