swagger: "2.0"
info: 
  version: "1.0"
  title: Test application
paths:
  /user:
    get:
      description: Returns all users
      produces:
        - application/json
      responses:
        '200':
          description: A list of users
          schema: 
            type: array
            items:
              $ref: '#/definitions/User'
definitions:
  User:
    required:
      - id
      - username
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string
