queryParameters:
  page:
    displayName: Page
    type: number
    description: The page of the results to return.
    example: 1
    default: 1
    required: false
  count:
    displayName: Count
    type: number
    description: The number of results per page.
    example: 1
    default: 10
    required: false