get:
  description: Returns the an Assertion with the appropriate ID.
  responses:
    200:
      body:
          application/json:
            schema: issuer-organization
            example: !include /examples/assertion/get/200.json
    404:
      body:
          application/json:
            example: !include /examples/assertion/get/404.json
put:
  description: Updates a Assertion of the given ID.
  responses:
    200:
      body:
          application/json:
            example: !include /examples/assertion/put/200.json
    404:
      body:
          application/json:
            example: !include /examples/assertion/put/404.json
    409:
      body:
          application/json:
            example: !include /examples/assertion/put/409.json
delete:
  description: Deletes an Assertion with the given ID.
  responses:
    200:
      body:
          application/json:
            example: !include /examples/assertion/delete/200.json
    404:
      body:
          application/json:
            example: !include /examples/assertion/delete/404.json